image: node:16.10.0

pipelines:
 default:
   - step:
       name: Install, Unit tests, e2e tests, Build
       caches:
         - node
       deployment: test
       script:
         - npm install
         - npm install -g @angular/cli 
         - ng build --prod 
         - echo "$(ls -la dist/)" 
         - scp -r dist/ root@179.43.121.110 -p 5641:/home/poscloud/public_html/poscloud2