image: node:8
pipelines: 
  default: 
    - step: 
       caches: 
         - node 
       script: # Modify the commands below to build your repository. 
          #- echo "$(ls -la)" 
          - npm install 
          - npm install -g @angular/cli 
          - ng build --prod 
          - echo "$(ls -la dist/)" 
          - scp -r dist/ root@179.43.121.110:5641:/home/poscloud/public_html/poscloud2