# Etapa de construcción
FROM node:14 as build-step
RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN npm install --legacy-peer-deps
RUN npm install -g @angular/cli
RUN npm run build:prod

# Etapa de producción
FROM nginx:stable
COPY --from=build-step /app/dist /usr/share/nginx/html
