export const environment = {
  production: false,
  api: 'http://localhost:300',
  apiv2: 'http://localhost:308',
  apiPrint: 'http://localhost:302',
  apiStorage: 'https://api-storage.poscloud.ar',
  apiTiendaNube: 'http://localhost:305',
  feAr: 'http://localhost:307',
  // api: 'https://d-api-v1.poscloud.ar',
  // apiv2: 'https://d-api-v2.poscloud.ar',
  // apiPrint: 'https://d-api-print.poscloud.ar',
  // apiStorage: 'https://d-api-storage.poscloud.ar',
  // apiTiendaNube: 'https://d-api-tiendanube.poscloud.ar',
  // feAr: 'https://d-fe-ar.poscloud.ar',
};
