import { IAttribute } from '@types';
import { Model } from '../model/model.model';

export function getCancellationTypeAttributes(): IAttribute[] {
  return Model.getAttributes([
    {
      name: 'origin.transactionMovement',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'origin.name',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'destination.transactionMovement',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'destination.name',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'automaticSelection',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'boolean',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'modifyBalance',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'boolean',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'requestAutomatic',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'boolean',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'requestCompany',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'boolean',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'requestStatusOrigin',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
    {
      name: 'stateOrigin',
      visible: true,
      disabled: false,
      filter: true,
      defaultFilter: null,
      datatype: 'string',
      project: null,
      align: 'left',
      required: false,
    },
  ]);
}
