FROM node:16.13.1

RUN mkdir -p /app
WORKDIR /app

COPY services/api-v2/package.json .
RUN npm install -g npm@8.7.0
RUN npm install
RUN npm install -g typescript@3.2.1
RUN npm install -g ts-node@7.0.1
COPY services/api-v2/ .

CMD [ "npm", "run", "dev" ]