export enum BusinessModel {
  Kiosco = 'kiosco',
  Supermercado = 'supermercado',
  Restaurante = 'restaurante',
  Mayorista = 'mayorista',
  Minorista = 'minorista',
  Panaderia = 'panaderia',
  TiendaRopa = 'tienda-ropa',
  Bar = 'bar',
  Estetica = 'estetica',
  Peluqueria = 'peluqueria',
  SuscripcionesYMembresias = 'suscripciones-y-membresias',
  Asociacion = 'asociacion',
  Otros = 'otros',
}
