export let attributes = [
  {
    name: 'VATPeriod',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'type.name',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'number',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'number',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'letter',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'center',
    required: false,
  },
  {
    name: 'origin',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'number',
    project: `{"$toString" : "$origin"}`,
    align: 'center',
    required: false,
  },
  {
    name: 'company.name',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'company.identificationValue',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'totalPrice',
    visible: true,
    disabled: false,
    filter: true,
    datatype: 'currency',
    project: `{"$toString" : "$totalPrice"}`,
    align: 'right',
    required: false,
  },
  {
    name: 'state',
    visible: true,
    disabled: false,
    filter: false,
    datatype: 'string',
    defaultFilter: `{ "$eq": "Abierto" }`,
    align: 'left',
    required: true,
  },

  {
    name: 'type.isSubscription',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'boolean',
    defaultFilter: `{ "$ne": "false" }`,
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'company._id',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'madein',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    defaultFilter: `{ "$eq": "subscription" }`,
    project: null,
    align: 'left',
    required: true,
  },

  {
    name: 'observation',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },

  {
    name: 'balance',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'currency',
    project: `{"$toString" : "$balance"}`,
    align: 'right',
    required: false,
  },

  {
    name: 'orderNumber',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'number',
    project: null,
    align: 'right',
    required: false,
  },

  {
    name: 'basePrice',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'currency',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'exempt',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'currency',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'discountAmount',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'currency',
    project: null,
    align: 'right',
    required: false,
  },
  {
    name: 'discountPercent',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'percent',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'wooId',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'updateDate',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'date',
    project: null,
    align: 'left',
    required: true,
  },

  {
    name: 'type.transactionMovement',
    visible: false,
    disabled: false,
    defaultFilter: `{ "$eq": "Venta" }`,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'type.electronics',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'type.allowEdit',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'boolean',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'type.allowDelete',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'boolean',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'type.electronics',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'boolean',
    project: null,
    align: 'left',
    required: true,
  },

  {
    name: 'type.readLayout',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'type.expirationDate',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'meliId',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'CAE',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: 'endDate2',
    visible: false,
    disabled: true,
    filter: false,
    datatype: 'date',
    project: `"$endDate"`,
    align: 'right',
    required: true,
  },

  {
    name: 'creationUser.name',
    visible: false,
    disabled: false,
    filter: false,
    datatype: 'string',
    project: null,
    align: 'left',
    required: false,
  },
  {
    name: '_id',
    visible: false,
    disabled: false,
    filter: true,
    datatype: 'string',
    project: null,
    align: 'left',
    required: true,
  },
  {
    name: 'operationType',
    visible: false,
    disabled: true,
    filter: false,
    datatype: 'string',
    defaultFilter: `{ "$ne": "D" }`,
    project: null,
    align: 'left',
    required: true,
  },
];
