name: Deploy Api v1 to Don Web

on:
  push:
    branches: [dev]
    paths:
      - "services/api-v1/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: dev

    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker rm -f api-poscloud || true

      - name: Construir y ejecutar contenedor Docker
        run: docker build -t api-poscloud -f services/api-v1/Dockerfile.dev . && docker run -v /home:/home --restart unless-stopped --net host --name api-poscloud -d -it -p 300:300 api-poscloud
