name: Testing
on:
  push:
    branches: [ testing ]
  workflow_dispatch:
jobs:
  build:
    runs-on: dev
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build:dev
      - run: cp -r ./dist/* /var/www/html/