name: Deploy to GitHub Pages

on:
  push:
    branches:
      - testing
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Build production
        run: npm run build:prod

      - name: Build testing
        run: npm run build:test

      - name: Deploy to GitHub Pages - Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "prod.poscloud.ar" > dist/prod/CNAME
          gh-pages -d dist/prod -b gh-pages --dotfiles --no-silent

      - name: Deploy to GitHub Pages - Testing
        if: github.ref == 'refs/heads/testing'
        run: |
          echo "test.poscloud.ar" > dist/test/CNAME
          gh-pages -d dist/test -b gh-pages --dotfiles --no-silent
