name: Build and Deploy prod.poscloud.ar

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'services/**'


jobs:
  build-and-deploy:
    runs-on: [prod]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Docker image
      run: docker build -t build-system -f Dockerfile.dev .

    - name: Backup current files
      run: |
        if [ -d "/home/system" ]; then
          mv /home/system /home/system_backup
          mkdir /home/system
        fi

    - name: Clean up backup
      run: |
        if [ -d "/home/system_backup" ]; then
          rm -rf /home/system_backup
        fi

    - name: Run Docker container
      run: docker run -v /home/system:/home/system build-system
      
    - name: Stop and remove existing container
      run: |
        docker stop system-poscloud || true
        docker rm -f system-poscloud || true
