name: Deploy to DonWeb Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: prod
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t build-system -f Dockerfile.dev .
      
      - name: Crear Carpeta de Version con Fecha
        run: |
          fecha=$(date "+%Y%m%d")
          mkdir -p /home/system/version/$fecha
  
      - name: Copiar Archivos y Eliminar Excepto /version
        run: |
          cp -r /home/system/* /home/system/version/$fecha/
          find /home/system/ -maxdepth 1 ! -name version -exec rm -r {} \;
  
      - name: Copiar Archivos y Eliminar Excepto /version
        run: |
          cp -r /home/system/* /home/system/version/$TAG/
          find /home/system/ -maxdepth 1 ! -name version -exec rm -r {} \;

      - name: Run Docker container
        run: docker run -v /ruta/en/tu/host:/home/system build-system

      - name: Stop and remove existing container
        run: |
          docker stop system-poscloud || true
          docker rm -f system-poscloud || true
      
