name: Deploy to DonWeb Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: prod
    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: |
          docker stop system-poscloud || true
          docker rm -f system-poscloud || true

      - name: Build Docker image
        run: docker build -t system-poscloud -f Dockerfile.dev .

      - name: Run Docker container
        run: docker run  --publish 304:80 --restart unless-stopped --net host --name system-poscloud -d -it system-poscloud