name: Deploy to DonWeb Main

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Run Docker Container
        run: |
          docker stop system-poscloud || true
          docker rm -f system-poscloud || true
          
          docker build -t system-poscloud -f Dockerfile.dev .
          docker run -v /home:/home --restart unless-stopped --net host --name system-poscloud -d -it -p 304:80 system-poscloud
