name: Release

on:
  push:
    branches:
      - main

jobs:
   release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Build Changelog
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
            configuration: "configuration.json"
            owner: "mikepenz"
            repo: "release-changelog-builder-action"
            ignorePreReleases: "false"
            fromTag: "0.3.0"
            toTag: "0.5.0"
            token: ${{ secrets.PAT }}

