name: Deploy Storage to Don Web

on:
  push:
    branches: [dev]
    paths:
      - "services/storage/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: dev

    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_REGION: ${{ secrets.S3_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker rm -f api-storage-poscloud || true

      - name: Build Docker image
        run: docker build -t api-storage-poscloud -f services/storage/Dockerfile .

      - name: Run Docker container
        run: |
          docker run \
            -v /home:/home \
            --restart unless-stopped \
            --net host \
            --name api-storage-poscloud \
            -e TOKEN_SECRET=${TOKEN_SECRET} \
            -e S3_ACCESS_KEY=${S3_ACCESS_KEY} \
            -e S3_SECRET_KEY=${S3_SECRET_KEY} \
            -e S3_BUCKET=${S3_BUCKET} \
            -e S3_REGION=${S3_REGION} \
            -d -it -p 303:303 api-storage-poscloud
