name: Deploy System DEV

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "services/**"

jobs:
  deploy-donweb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"  # Use Node.js 14 as Angular may not be fully compatible with Node 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Backup current files
        run: |
          sudo mv /home/system /home/system_backup
          sudo mkdir /home/system

      - name: Build Angular app
        run: |
          cd /path/to/your/angular/app
          ng build --prod

      - name: Clean up backup
        run: |
            if [ -d "/home/system_backup" ]; then
              rm -rf /home/system_backup
            fi
        

      - name: Move new build to /home/system
        run: sudo mv /path/to/your/angular/app/dist/* /home/system/

      - name: Build Docker image
        run: docker build -t build-system -f Dockerfile.dev .

      - name: Run Docker container
        run: docker run -v /home/system:/home/system build-system

      - name: Stop and remove existing container
        run: |
          docker stop system-poscloud || true
          docker rm -f system-poscloud || true
