name: PROD API Tienda Nube (Manual)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Razón del deploy manual'
        required: false
        default: 'Deploy manual de Tienda Nube'

jobs:
  deploy-donweb:
    runs-on: prod

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      TIENDA_NUBE_URI: ${{ secrets.TIENDA_NUBE_URI }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      POSCLOUD_URI: ${{ secrets.POSCLOUD_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker rm -f api-tienda-nube || true

      - name: Build Docker image
        run: docker build -t api-tienda-nube -f services/tienda-nube/Dockerfile.main .

      - name: Run Docker container
        run: |
          docker run \
            -e MONGO_URL=${MONGO_URL} \
            -e TIENDA_NUBE_URI=${TIENDA_NUBE_URI} \
            -e TOKEN_SECRET=${TOKEN_SECRET} \
            -e POSCLOUD_URI=${POSCLOUD_URI} \
            -v /home:/home \
            --restart unless-stopped \
            --net host \
            --name api-tienda-nube \
            -d -it -p 305:305 api-tienda-nube
