name: Deploy Tienda Nube to Don Web

on:
  push:
    branches: [main]
    paths:
      - "services/tienda-nube/**"
  workflow_dispatch:

jobs:
  deploy-donweb:
    runs-on: prod

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      TIENDA_NUBE_URI: ${{ secrets.TIENDA_NUBE_URI }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      URL_POSTCLOUD: ${{ secrets.URL_POSTCLOUD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker rm -f api-tienda-nube || true

      - name: Build Docker image
        run: docker build -t api-tienda-nube -f services/tienda-nube/Dockerfile.main .

      - name: Run Docker container
        run: |
          docker run \
            -e MONGO_URL=${MONGO_URL} \
            -e TIENDA_NUBE_URI=${TIENDA_NUBE_URI} \
            -e TOKEN_SECRET=${TOKEN_SECRET} \
            -e URL_POSTCLOUD=${URL_POSTCLOUD} \
            -v /home:/home \
            --restart unless-stopped \
            --net host \
            --name api-tienda-nube \
            -d -it -p 305:305 api-tienda-nube
